baseurl: /my-blog
permalink: date

#theme: jekyll-theme-cayman
#theme: jekyll-theme-slate
#theme: jekyll-theme-merlot
#theme: jekyll-theme-time-machine
#theme: jekyll-theme-minimal
#theme: jekyll-theme-leap-day
#theme: jekyll-theme-modernist
#theme: jekyll-theme-hacker
#theme: jekyll-theme-midnight
#theme: jekyll-theme-architect
#theme: jekyll-theme-tactile
#theme: jekyll-theme-dinky
